# Generated by Django 5.1 on 2024-08-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('error', 'Error'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
    ]
